version: "3.8"
services:
 db:
  image: postgres:14.1-alpine
  restart: always
  environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=pstpmn11
  ports:
    - '5432:5432'
  volumes: 
    - ./backup/db:/var/lib/postgresql/data

 adminer:
  image: adminer
  restart: always
  ports:
    - 8080:8080